package:
  name: r-projecttemplate
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.6"

source:
  fn: ProjectTemplate_0.6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/ProjectTemplate_0.6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/ProjectTemplate/ProjectTemplate_0.6.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: foreign, reshape, plyr, stringr, ggplot2, lubridate, log4r (>= 0.1-5), DBI, RMySQL, RSQLite, gdata, RODBC, RJDBC, xlsx, tuneR, pixmap, data.table, RPostgreSQL, GetoptLong, whisker, testthat
requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ProjectTemplate')" # [not win]
    - "\"%R%\" -e \"library('ProjectTemplate')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://projecttemplate.net'

  license: Artistic-2.0
  summary: !!python/unicode 'ProjectTemplate provides functions to automatically build a directory
    structure for a new R project. Using this structure, ProjectTemplate automates data
    loading, preprocessing, library importing and unit testing.'


# The original CRAN metadata for this package was:

# Package: ProjectTemplate
# Type: Package
# Title: Automates the creation of new statistical analysis projects.
# Version: 0.6
# Date: 2014-10-05
# Authors@R: c( person("Aleksandar", "Blagotic", role = "ctb"), person("Diego", "Valle-Jones", role = "ctb"), person("Jeffrey", "Breen", role = "ctb"), person("Joakim", "Lundborg", role = "ctb"), person("John Myles", "White", role = c("aut", "cph")), person("Josh", "Bode", role = "ctb"), person("Kenton", "White", role = "ctb"), person("Kirill", "Mueller", role = c("ctb", "cre"), email = "krlmlr+r@mailbox.org"), person("Matteo", "Redaelli", role = "ctb"), person("Noah", "Lorang", role = "ctb"), person("Patrick", "Schalk", role = "ctb"))
# Description: ProjectTemplate provides functions to automatically build a directory structure for a new R project. Using this structure, ProjectTemplate automates data loading, preprocessing, library importing and unit testing.
# License: Artistic-2.0
# LazyLoad: yes
# Depends: R (>= 2.7)
# Suggests: foreign, reshape, plyr, stringr, ggplot2, lubridate, log4r (>= 0.1-5), DBI, RMySQL, RSQLite, gdata, RODBC, RJDBC, xlsx, tuneR, pixmap, data.table, RPostgreSQL, GetoptLong, whisker, testthat
# URL: http://projecttemplate.net
# BugReports: https://github.com/johnmyleswhite/ProjectTemplate/issues
# Collate: 'xport.reader.R' 'xlsx.reader.R' 'xls.reader.R' 'wsv.reader.R' 'url.reader.R' 'tsv.reader.R' 'systat.reader.R' 'stata.reader.R' 'require.package.R' 'sql.reader.R' 'spss.reader.R' 'rdata.reader.R' 'r.reader.R' 'ppm.reader.R' 'octave.reader.R' 'mtp.reader.R' 'mp3.reader.R' 'file.reader.R' 'epiinfo.reader.R' 'dbf.reader.R' 'db.reader.R' 'csv2.reader.R' 'csv.reader.R' 'arff.reader.R' 'preinstalled.readers.R' 'add.extension.R' 'cache.R' 'cache.name.R' 'cache.project.R' 'clean.variable.name.R' 'create.project.R' 'translate.dcf.R' 'default.config.R' 'get.project.R' 'help.R' 'load.project.R' 'migrate.project.R' 'new.config.R' 'reload.project.R' 'run.project.R' 'show.project.R' 'stub.tests.R' 'test.project.R'
# Packaged: 2014-10-05 21:51:27 UTC; muelleki
# Author: Aleksandar Blagotic [ctb], Diego Valle-Jones [ctb], Jeffrey Breen [ctb], Joakim Lundborg [ctb], John Myles White [aut, cph], Josh Bode [ctb], Kenton White [ctb], Kirill Mueller [ctb, cre], Matteo Redaelli [ctb], Noah Lorang [ctb], Patrick Schalk [ctb]
# Maintainer: Kirill Mueller <krlmlr+r@mailbox.org>
# NeedsCompilation: no
# Repository: CRAN
# Date/Publication: 2014-10-06 00:57:23

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
