package:
  name: r-loo
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1.3"

source:
  fn: loo_0.1.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/loo_0.1.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/loo/loo_0.1.3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, testthat
requirements:
  build:
    - r
    - r-matrixstats >=0.14.1

  run:
    - r
    - r-matrixstats >=0.14.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('loo')" # [not win]
    - "\"%R%\" -e \"library('loo')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://github.com/jgabry/loo'

  license: GPL (>= 3)
  summary: !!python/unicode 'We efficiently approximate leave-one-out cross-validation (LOO)
    using Pareto smoothed importance sampling (PSIS), a new procedure for regularizing
    importance weights. As a byproduct of our calculations, we also obtain approximate
    standard errors for estimated predictive errors, and for the comparison of predictive
    errors between two models. We also compute the widely applicable information criterion
    (WAIC).'


# The original CRAN metadata for this package was:

# Package: loo
# Type: Package
# Title: Efficient Leave-One-Out Cross-Validation and WAIC for Bayesian Models
# Version: 0.1.3
# Date: 2015-09-17
# Authors@R: c(person("Aki", "Vehtari", email = "Aki.Vehtari@aalto.fi", role = c("aut")), person("Andrew", "Gelman", email = "gelman@stat.columbia.edu", role = c("aut")), person("Jonah", "Gabry", email = "jsg2201@columbia.edu", role = c("cre", "aut")), person("Juho", "Piironen", role = c("ctb")), person("Ben", "Goodrich", role = c("ctb")))
# Maintainer: Jonah Gabry <jsg2201@columbia.edu>
# URL: https://github.com/jgabry/loo
# BugReports: https://github.com/jgabry/loo/issues
# Description: We efficiently approximate leave-one-out cross-validation (LOO) using Pareto smoothed importance sampling (PSIS), a new procedure for regularizing importance weights. As a byproduct of our calculations, we also obtain approximate standard errors for estimated predictive errors, and for the comparison of predictive errors between two models. We also compute the widely applicable information criterion (WAIC).
# License: GPL (>= 3)
# LazyData: TRUE
# Depends: R (>= 3.1.2)
# Imports: graphics, matrixStats (>= 0.14.1), parallel, stats
# Suggests: knitr, testthat
# VignetteBuilder: knitr
# NeedsCompilation: no
# Packaged: 2015-09-17 21:51:15 UTC; jgabry
# Author: Aki Vehtari [aut], Andrew Gelman [aut], Jonah Gabry [cre, aut], Juho Piironen [ctb], Ben Goodrich [ctb]
# Repository: CRAN
# Date/Publication: 2015-09-18 08:58:41

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
