package:
  name: r-rstanmulticore
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.2.0"

source:
  fn: rstanmulticore-0.2.0.tar.gz
  url:
    - https://github.com/ihrke/rstanmulticore/archive/rstanmulticore-0.2.0.tar.gz

  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r
    - r-rstan
#    - r-parallel

  run:
    - r
    - r-rstan
#    - r-parallel

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rstanmulticore')" # [not win]
    - "\"%R%\" -e \"library('rstanmulticore')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://www.stat.cmu.edu/~nmv/2015/05/01/rstanmulticore-a-cross-platform-r-package-to-automatically-run-rstan-mcmc-chains-in-parallel/'

  license: MIT + file LICENSE
  summary: !!python/unicode 'A cross-platform (Windows, Linux, and Mac) R package to parallelize RStan MCMC chains across multiple cores. The syntax is very simple: replace calls to stan(...) with pstan(...).'


# The original CRAN metadata for this package was:
# Package: rstanmulticore
# Title: Transparently run RStan MCMC chains on multiple cores
# Version: 0.2.0
# Authors@R: person("Nathan", "VanHoudnos", , "nathanvan@gmail.com", role = c("aut", "cre"))
# Description: A cross-platform (Windows, Linux, and Mac) R package to parallelize RStan MCMC chains across multiple cores. The syntax is very simple: replace calls to stan(...) with pstan(...).
# Depends: R (>= 2.14.0),
#         rstan,
#         parallel
# Suggests: testthat, knitr
# License: MIT + file LICENSE
# LazyData: true
# VignetteBuilder: knitr


# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
