package:
  name: r-mice
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.22"

source:
  fn: mice_2.22.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/mice_2.22.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/mice/mice_2.22.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: AGD, gamlss, lme4, mitools, nlme, pan, survival, Zelig
requirements:
  build:
    - r
    - r-mass # [not win]
    - r-rcpp
    - r-lattice # [not win]
    - r-nnet # [not win]
    - r-randomforest
    - r-rpart # [not win]
    - gcc # [not win]

  run:
    - r
    - r-mass # [not win]
    - r-rcpp
    - r-lattice # [not win]
    - r-nnet # [not win]
    - r-randomforest
    - r-rpart # [not win]
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('mice')" # [not win]
    - "\"%R%\" -e \"library('mice')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://www.stefvanbuuren.nl , http://www.multiple-imputation.com'

  license: GPL-2 | GPL-3
  summary: !!python/unicode 'Multiple imputation using Fully Conditional Specification (FCS)
    implemented by the MICE algorithm. Each variable has its own imputation model. Built-in
    imputation models are provided for continuous data (predictive mean matching, normal),
    binary data (logistic regression), unordered categorical data (polytomous logistic
    regression) and ordered categorical data (proportional odds). MICE can also impute
    continuous two-level data (normal model, pan, second-level variables). Passive imputation
    can be used to maintain consistency between variables. Various diagnostic plots
    are available to inspect the quality of the imputations.'


# The original CRAN metadata for this package was:

# Package: mice
# Type: Package
# Version: 2.22
# Title: Multivariate Imputation by Chained Equations
# Date: 2014-06-10
# Authors@R: c(person("Stef", "van Buuren", role = c("aut","cre"), email = "stef.vanbuuren@tno.nl"), person("Karin", "Groothuis-Oudshoorn", role = "aut", email = "c.g.m.oudshoorn@utwente.nl"), person("Alexander", "Robitzsch", role = "ctb", email = "a.robitzsch@bifie.at"), person("Gerko","Vink", role = "ctb", email = "g.vink@uu.nl"), person("Lisa","Doove", role = "ctb", email = "lisa.doove@ppw.kuleuven.be"), person("Shahab","Jolani", role = "ctb", email = "s.jolani@uu.nl"))
# Maintainer: Stef van Buuren <stef.vanbuuren@tno.nl>
# Depends: R (>= 2.10.0), methods, Rcpp (>= 0.10.6), lattice
# Imports: MASS, nnet, randomForest, rpart
# Suggests: AGD, gamlss, lme4, mitools, nlme, pan, survival, Zelig
# LinkingTo: Rcpp
# Description: Multiple imputation using Fully Conditional Specification (FCS) implemented by the MICE algorithm. Each variable has its own imputation model. Built-in imputation models are provided for continuous data (predictive mean matching, normal), binary data (logistic regression), unordered categorical data (polytomous logistic regression) and ordered categorical data (proportional odds). MICE can also impute continuous two-level data (normal model, pan, second-level variables). Passive imputation can be used to maintain consistency between variables. Various diagnostic plots are available to inspect the quality of the imputations.
# License: GPL-2 | GPL-3
# LazyLoad: yes
# LazyData: yes
# URL: http://www.stefvanbuuren.nl , http://www.multiple-imputation.com
# Packaged: 2014-06-11 19:53:11 UTC; stefvanbuuren
# Author: Stef van Buuren [aut, cre], Karin Groothuis-Oudshoorn [aut], Alexander Robitzsch [ctb], Gerko Vink [ctb], Lisa Doove [ctb], Shahab Jolani [ctb]
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-06-11 23:31:32

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
