language: python
compiler: clang
sudo: false
python:
- '2.7'
install:
- export CXX="clang++" 
- export CC="clang"
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda config --add channels r
- conda install conda-build
- conda install anaconda-client anaconda anaconda-build binstar
- conda info -a
- conda install r r-essentials
script:
- bash build_and_upload.sh
env:
  global:
  - secure: MWxFHWz7gSxXWDGqqh7lkH6dAuWpd0pffUEXvvEDNLPIDCUki4NQxwfyAUdRp5Ai+GYFaYSrZ+Q3D313pEiouc7BexUqvfSqpA6oeIAtG1L3eXhBTv7joIOtn0xWEyWX24YMI7gE7hN6gw2X+FtZPXBfBb+PD8c2oktkVkxq0H+8XiHlnFh+NvBlsCOG1WcbNbRGEDKlMD3x98XtPLt6Q93k5qG4ZdBiX3kT5ap2UIaZp+e6qMxqGX+nbbvSmKjtf6CsCUfDzEyZrcxt198IKQzr//+PAAaN2bS0sx3ho7jhO93CSHz717EP4nC0Qg9TqC1B1lDDDUbJsjyva0wWH5UD5Jv0X5c29oqqhpYt1WGpb9pdAZpNN60Vd4+yDObPDu+rsuIemC2IYg2b9lABkAdaKnJMQqKgx3aGcresCPYXnrJRvZS3dG6Q6Jpw8dkA3FRua1iu2dUn793otpI1q66SVMbMYGFjG572ApdvnDu2PBcW0H6C8dEFaWscWsi5SnVq7qfHkt08dm/wGAm2OJeDdJzWhogMVmTTL1nIFfsNBLVhdEfaSEqsZpoJtTdNHvAzkaadPuavIArp+mND8J5cf1kLe3MOsLM5WT7RDMqmdfl1G/3NAtV0O0ji2IJEBukE75tizA+SdGF4Bhb5B6hiQVfnkzLL/0O8I3y9NmA=
