package:
  name: r-pbapply
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.1_3"

source:
  fn: pbapply_1.1-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/pbapply_1.1-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/pbapply/pbapply_1.1-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('pbapply')" # [not win]
    - "\"%R%\" -e \"library('pbapply')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/psolymos/pbapply
  license: GPL-2
  summary: A lightweight package that adds progress bar to vectorized R functions ('*apply').
    The implementation can easily be added to functions, where showing the progress
    is useful for the user (e.g. bootstrap).

# The original CRAN metadata for this package was:

# Package: pbapply
# Type: Package
# Title: Adding Progress Bar to '*apply' Functions
# Version: 1.1-3
# Date: 2015-10-24
# Author: Peter Solymos
# Maintainer: Peter Solymos <solymos@ualberta.ca>
# Description: A lightweight package that adds progress bar to vectorized R functions ('*apply'). The implementation can easily be added to functions, where showing the progress is useful for the user (e.g. bootstrap).
# Depends: R (>= 3.2.0)
# License: GPL-2
# URL: https://github.com/psolymos/pbapply
# LazyLoad: yes
# NeedsCompilation: no
# Packaged: 2015-11-24 21:31:30 UTC; Peter
# Repository: CRAN
# Date/Publication: 2015-11-24 23:59:18

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
