package:
  name: r-rstan
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.8.0"

source:
  fn: rstan_2.8.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/rstan_2.8.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/rstan/rstan_2.8.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: RUnit, RcppEigen, BH (>= 1.58), StanHeaders (>= 2.8.0), parallel, KernSmooth, RCurl, loo, rstudioapi, Matrix
requirements:
  build:
    - r
    - r-bh >=1.58
    - r-rcpp
    - r-rcppeigen
    - r-stanheaders >=2.8.0
    - r-ggplot2 >=1.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - gcc # [not win]

  run:
    - r
    - r-bh >=1.58
    - r-rcpp
    - r-rcppeigen
    - r-stanheaders >=2.8.0
    - r-ggplot2 >=1.0.0
    - r-gridextra >=2.0.0
    - r-inline
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('rstan')" # [not win]
    - "\"%R%\" -e \"library('rstan')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'https://groups.google.com/forum/#!forum/stan-users, http://mc-stan.org'

  license: GPL (>= 3)
  summary: !!python/unicode 'User-facing R functions are provided by this package to parse, compile,
    test, estimate, and analyze Stan models by accessing the header-only Stan library
    provided by the ''StanHeaders'' package. The Stan project develops a probabilistic
    programming language that implements full Bayesian statistical inference via Markov
    Chain Monte Carlo and (optionally penalized) maximum likelihood estimation via optimization.
    In both cases, automatic differentiation is used to quickly and accurately evaluate
    gradients without burdening the user with the need to derive the partial derivatives.'


# The original CRAN metadata for this package was:

# Package: rstan
# Type: Package
# Title: R Interface to Stan
# Version: 2.8.0
# Date: 2015-09-19
# Authors@R: c(person("Jiqiang", "Guo", email = "guojq28@gmail.com", role = "aut"), person("Daniel", "Lee", role = "ctb"), person("Krzysztof", "Sakrejda", role = "ctb"), person("Jonah", "Gabry", role = "aut"), person("Ben", "Goodrich", email = "benjamin.goodrich@columbia.edu", role = c("cre", "aut")), person("Joel", "de Guzman", role = "cph", comment = "Boost"), person("Eric", "Niebler", role = "cph",   comment = "Boost"), person("Thomas", "Heller", role = "cph",  comment = "Boost"), person("John", "Fletcher", role = "cph",  comment = "Boost"))
# Description: User-facing R functions are provided by this package to parse, compile, test, estimate, and analyze Stan models by accessing the header-only Stan library provided by the 'StanHeaders' package. The Stan project develops a probabilistic programming language that implements full Bayesian statistical inference via Markov Chain Monte Carlo and (optionally penalized) maximum likelihood estimation via optimization. In both cases, automatic differentiation is used to quickly and accurately evaluate gradients without burdening the user with the need to derive the partial derivatives.
# License: GPL (>= 3)
# NeedsCompilation: yes
# Imports: stats4, inline, gridExtra (>= 2.0.0)
# Depends: R (>= 3.0.2), Rcpp (>= 0.11.0), methods, ggplot2 (>= 1.0.0)
# LinkingTo: Rcpp, RcppEigen, BH (>= 1.58), StanHeaders (>= 2.8.0)
# Suggests: RUnit, RcppEigen, BH (>= 1.58), StanHeaders (>= 2.8.0), parallel, KernSmooth, RCurl, loo, rstudioapi, Matrix
# URL: https://groups.google.com/forum/#!forum/stan-users, http://mc-stan.org
# Packaged: 2015-09-19 14:48:38 UTC; goodrich
# Author: Jiqiang Guo [aut], Daniel Lee [ctb], Krzysztof Sakrejda [ctb], Jonah Gabry [aut], Ben Goodrich [cre, aut], Joel de Guzman [cph] (Boost), Eric Niebler [cph] (Boost), Thomas Heller [cph] (Boost), John Fletcher [cph] (Boost)
# Maintainer: Ben Goodrich <benjamin.goodrich@columbia.edu>
# Repository: CRAN
# Date/Publication: 2015-09-19 19:50:34

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
