package:
  name: r-modeest
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.1"

source:
  fn: modeest_2.1.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/modeest_2.1.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/modeest/modeest_2.1.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: stats, evd, fBasics, stabledist, VGAM
requirements:
  build:
    - r
    - gcc # [not win]

  run:
    - r
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('modeest')" # [not win]
    - "\"%R%\" -e \"library('modeest')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL (>= 2)
  summary: !!python/unicode 'This package provides estimators of the mode of univariate unimodal
    data or univariate unimodal distributions'


# The original CRAN metadata for this package was:

# Package: modeest
# Type: Package
# Title: Mode Estimation
# Version: 2.1
# Date: 2012-10-15
# Author: P. PONCET
# Description: This package provides estimators of the mode of univariate unimodal data or univariate unimodal distributions
# Maintainer: P. PONCET <paulponcet@yahoo.fr>
# Depends: R (>= 2.12.0)
# Suggests: stats, evd, fBasics, stabledist, VGAM
# License: GPL (>= 2)
# Packaged: 2012-10-15 09:04:15 UTC; YL1101
# Repository: CRAN
# Date/Publication: 2012-10-15 11:21:35
# NeedsCompilation: yes

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
