package:
  name: r-mcmcpack
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.3_3"

source:
  fn: MCMCpack_1.3-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/MCMCpack_1.3-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/MCMCpack/MCMCpack_1.3-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r
    - r-mass # [not win]
    - r-coda >=0.11_3
    - gcc # [not win]

  run:
    - r
    - r-mass # [not win]
    - r-coda >=0.11_3
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('MCMCpack')" # [not win]
    - "\"%R%\" -e \"library('MCMCpack')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://mcmcpack.wustl.edu
  license: GPL-3
  summary: This package contains functions to perform Bayesian inference using posterior simulation
    for a number of statistical models. Most simulation is done in compiled C++ written
    in the Scythe Statistical Library Version 1.0.3. All models return coda mcmc objects
    that can then be summarized using the coda package.  MCMCpack also contains some
    useful utility functions, including some additional density functions and pseudo-random
    number generators for statistical distributions, a general purpose Metropolis sampling
    algorithm, and tools for visualization.

# The original CRAN metadata for this package was:

# Package: MCMCpack
# Version: 1.3-3
# Date: 2013-5-1
# Title: Markov chain Monte Carlo (MCMC) Package
# Author: Andrew D. Martin, Kevin M. Quinn, and Jong Hee Park
# Maintainer: Jong Hee Park <jongheepark@snu.ac.kr>
# Depends: R (>= 2.10.0), coda (>= 0.11-3), MASS, stats
# Description: This package contains functions to perform Bayesian inference using posterior simulation for a number of statistical models. Most simulation is done in compiled C++ written in the Scythe Statistical Library Version 1.0.3. All models return coda mcmc objects that can then be summarized using the coda package.  MCMCpack also contains some useful utility functions, including some additional density functions and pseudo-random number generators for statistical distributions, a general purpose Metropolis sampling algorithm, and tools for visualization.
# License: GPL-3
# SystemRequirements: gcc (>= 4.0)
# URL: http://mcmcpack.wustl.edu
# Packaged: 2013-05-01 00:37:02 UTC; parkjonghee
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2013-05-01 07:02:08

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
