package:
  name: r-bayesfactor
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.9.12_2"

source:
  fn: BayesFactor_0.9.12-2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/BayesFactor_0.9.12-2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/BayesFactor/BayesFactor_0.9.12-2.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: doMC, foreach, testthat, knitr, markdown, arm, lme4, xtable, languageR
requirements:
  build:
    - r
    - r-matrix >=1.1_1 # [not win]
    - r-matrixmodels
    - r-rcpp >=0.11.2
    - r-rcppeigen >=0.3.2.2.0
    - r-coda
    - r-gtools
    - r-mvtnorm
    - r-pbapply
    - r-stringr
    - gcc # [not win]

  run:
    - r
    - r-matrix >=1.1_1 # [not win]
    - r-matrixmodels
    - r-rcpp >=0.11.2
    - r-rcppeigen >=0.3.2.2.0
    - r-coda
    - r-gtools
    - r-mvtnorm
    - r-pbapply
    - r-stringr
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('BayesFactor')" # [not win]
    - "\"%R%\" -e \"library('BayesFactor')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://bayesfactorpcl.r-forge.r-project.org/'

  license: GPL-2
  summary: !!python/unicode 'A suite of functions for computing various Bayes factors for simple
    designs, including contingency tables, one- and two-sample designs, one-way designs,
    general ANOVA designs, and linear regression.'


# The original CRAN metadata for this package was:

# Package: BayesFactor
# Type: Package
# Title: Computation of Bayes Factors for Common Designs
# Version: 0.9.12-2
# Date: 2015-09-19
# Authors@R: c(person("Richard D.", "Morey", role = c("aut", "cre"), email = "richarddmorey@gmail.com"), person("Jeffrey N.", "Rouder", role = "aut", email = "rouderj@missouri.edu"), person("Tahira", "Jamil", role = "ctb", email = "tahjamil@gmail.com"))
# Description: A suite of functions for computing various Bayes factors for simple designs, including contingency tables, one- and two-sample designs, one-way designs, general ANOVA designs, and linear regression.
# License: GPL-2
# VignetteBuilder: knitr
# Depends: R (>= 3.0.2), coda, Matrix (>= 1.1-1)
# Imports: pbapply, mvtnorm, stringr, utils, graphics, gtools, MatrixModels, Rcpp (>= 0.11.2), methods
# Suggests: doMC, foreach, testthat, knitr, markdown, arm, lme4, xtable, languageR
# URL: http://bayesfactorpcl.r-forge.r-project.org/
# BugReports: https://github.com/richarddmorey/BayesFactor/issues
# LazyLoad: yes
# LinkingTo: Rcpp (>= 0.11.2), RcppEigen (>= 0.3.2.2.0)
# NeedsCompilation: yes
# Packaged: 2015-09-19 10:57:22 UTC; richard
# Author: Richard D. Morey [aut, cre], Jeffrey N. Rouder [aut], Tahira Jamil [ctb]
# Maintainer: Richard D. Morey <richarddmorey@gmail.com>
# Repository: CRAN
# Date/Publication: 2015-09-19 19:50:23

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
