package:
  name: r-rwiener
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.2_0"

source:
  fn: RWiener_1.2-0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/RWiener_1.2-0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/RWiener/RWiener_1.2-0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: MASS
requirements:
  build:
    - r
    - gcc # [not win]

  run:
    - r
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('RWiener')" # [not win]
    - "\"%R%\" -e \"library('RWiener')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://sourceforge.net/projects/rwiener/
  license: GPL (>= 2)
  summary: This package provides Wiener process distribution functions, namely the Wiener first
    passage time density, CDF, quantile and random functions.

# The original CRAN metadata for this package was:

# Package: RWiener
# Version: 1.2-0
# Date: 2014-01-25
# Title: Wiener process distribution functions
# Authors@R: c(person("Dominik", "Wabersich",  role=c("aut", "cre"), email="dominik.wabersich@gmail.com"))
# Author: Dominik Wabersich
# Maintainer: Dominik Wabersich <dominik.wabersich@gmail.com>
# Depends: R (>= 2.15.0)
# Suggests: MASS
# License: GPL (>= 2)
# URL: https://sourceforge.net/projects/rwiener/
# Description: This package provides Wiener process distribution functions, namely the Wiener first passage time density, CDF, quantile and random functions.
# Packaged: 2014-01-25 19:14:46 UTC; yeagle
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-01-25 20:36:48

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
