package:
  name: r-ez
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "4.3"

source:
  fn: ez_4.3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/ez_4.3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/ez/ez_4.3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r
    - r-mass >=7.3_29 # [not win]
    - r-matrix >=1.0_6 # [not win]
    - r-car >=2.0_12
    - r-ggplot2 >=0.9.1
    - r-lme4 >=0.999999_0
    - r-mgcv >=1.7_13 # [not win]
    - r-plyr >=1.7.1
    - r-reshape2 >=1.2.1
    - r-scales >=0.2.1
    - r-stringr >=0.6.1

  run:
    - r
    - r-mass >=7.3_29 # [not win]
    - r-matrix >=1.0_6 # [not win]
    - r-car >=2.0_12
    - r-ggplot2 >=0.9.1
    - r-lme4 >=0.999999_0
    - r-mgcv >=1.7_13 # [not win]
    - r-plyr >=1.7.1
    - r-reshape2 >=1.2.1
    - r-scales >=0.2.1
    - r-stringr >=0.6.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('ez')" # [not win]
    - "\"%R%\" -e \"library('ez')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/mike-lawrence/ez
  license: GPL (>= 2)
  summary: Facilitates easy analysis of factorial experiments, including purely within-Ss designs
    (a.k.a. "repeated measures"), purely between-Ss designs, and mixed within-and-between-Ss
    designs. The functions in this package aim to provide simple, intuitive and consistent
    specification of data analysis and visualization. Visualization functions also include
    design visualization for pre-analysis data auditing, and correlation matrix visualization.
    Finally, this package includes functions for non-parametric analysis, including
    permutation tests and bootstrap resampling. The bootstrap function obtains predictions
    either by cell means or by more advanced/powerful mixed effects models, yielding
    predictions and confidence intervals that may be easily visualized at any level
    of the experiment's design.

# The original CRAN metadata for this package was:

# Package: ez
# Version: 4.3
# Date: 2015-11-10
# Title: Easy Analysis and Visualization of Factorial Experiments
# Author: Michael A. Lawrence <mike.lwrnc@gmail.com>
# Maintainer: Michael A. Lawrence <mike.lwrnc@gmail.com>
# URL: http://github.com/mike-lawrence/ez
# Depends: R (>= 3.0.0)
# Imports: car (>= 2.0-12), ggplot2 (>= 0.9.1), lme4 (>= 0.999999-0), MASS (>= 7.3-29), Matrix (>= 1.0-6), mgcv (>= 1.7-13), plyr (>= 1.7.1), reshape2 (>= 1.2.1), scales (>= 0.2.1), stringr (>= 0.6.1)
# Description: Facilitates easy analysis of factorial experiments, including purely within-Ss designs (a.k.a. "repeated measures"), purely between-Ss designs, and mixed within-and-between-Ss designs. The functions in this package aim to provide simple, intuitive and consistent specification of data analysis and visualization. Visualization functions also include design visualization for pre-analysis data auditing, and correlation matrix visualization. Finally, this package includes functions for non-parametric analysis, including permutation tests and bootstrap resampling. The bootstrap function obtains predictions either by cell means or by more advanced/powerful mixed effects models, yielding predictions and confidence intervals that may be easily visualized at any level of the experiment's design.
# License: GPL (>= 2)
# LazyLoad: yes
# ByteCompile: true
# NeedsCompilation: no
# Packaged: 2015-11-13 15:09:04 UTC; mike
# Repository: CRAN
# Date/Publication: 2015-11-13 23:53:58

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
