package:
  name: r-abind
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.4_3"

source:
  fn: abind_1.4-3.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/abind_1.4-3.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/abind/abind_1.4-3.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r

  run:
    - r

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('abind')" # [not win]
    - "\"%R%\" -e \"library('abind')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: LGPL (>= 2)
  summary: !!python/unicode 'Combine multidimensional arrays into a single array. This is a generalization
    of ''cbind'' and ''rbind''.  Works with vectors, matrices, and higher-dimensional
    arrays.  Also provides functions ''adrop'', ''asub'', and ''afill'' for manipulating,
    extracting and replacing data in arrays.'


# The original CRAN metadata for this package was:

# Package: abind
# Version: 1.4-3
# Date: 2015-03-05
# Title: Combine Multidimensional Arrays
# Author: Tony Plate <tplate@acm.org> and Richard Heiberger
# Maintainer: Tony Plate <tplate@acm.org>
# Description: Combine multidimensional arrays into a single array. This is a generalization of 'cbind' and 'rbind'.  Works with vectors, matrices, and higher-dimensional arrays.  Also provides functions 'adrop', 'asub', and 'afill' for manipulating, extracting and replacing data in arrays.
# Depends: R (>= 1.5.0)
# License: LGPL (>= 2)
# NeedsCompilation: no
# Packaged: 2015-03-13 03:29:01 UTC; tap
# Repository: CRAN
# Date/Publication: 2015-03-13 07:54:43

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
