package:
  name: r-sm
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "2.2_5.4"

source:
  fn: sm_2.2-5.4.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/sm_2.2-5.4.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/sm/sm_2.2-5.4.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: rpanel, tkrplot, rgl, misc3d, akima, gam
requirements:
  build:
    - r
    - gcc # [not win]

  run:
    - r
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sm')" # [not win]
    - "\"%R%\" -e \"library('sm')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://www.stats.gla.ac.uk/~adrian/sm'

  license: GPL (>= 2)
  summary: !!python/unicode 'This is software linked to the book ''Applied Smoothing Techniques
    for Data Analysis - The Kernel Approach with S-Plus Illustrations'' Oxford University
    Press.'


# The original CRAN metadata for this package was:

# Package: sm
# Type: Package
# Title: Smoothing methods for nonparametric regression and density estimation
# Version: 2.2-5.4
# Date: 2013-12-21
# Author: Adrian Bowman and Adelchi Azzalini.  Ported to R by B. D. Ripley <ripley@stats.ox.ac.uk> up to version 2.0, version 2.1 by Adrian Bowman and Adelchi Azzalini, version 2.2 by Adrian Bowman.
# Maintainer: Adrian Bowman <adrian.bowman@glasgow.ac.uk>
# Depends: R (>= 2.14.0)
# Suggests: rpanel, tkrplot, rgl, misc3d, akima, gam
# Description: This is software linked to the book 'Applied Smoothing Techniques for Data Analysis - The Kernel Approach with S-Plus Illustrations' Oxford University Press.
# License: GPL (>= 2)
# LazyData: TRUE
# URL: http://www.stats.gla.ac.uk/~adrian/sm
# Packaged: 2014-01-16 18:01:36 UTC; adrian
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-01-16 20:20:26

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
