package:
  name: r-readxl
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "0.1.0"

source:
  fn: readxl_0.1.0.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/readxl_0.1.0.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/readxl/readxl_0.1.0.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat
requirements:
  build:
    - r
    - r-rcpp >=0.11.5
    - gcc # [not win]

  run:
    - r
    - r-rcpp >=0.11.5
    - libgcc # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('readxl')" # [not win]
    - "\"%R%\" -e \"library('readxl')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  #home:
  license: GPL-3 + file LICENSE
  summary: !!python/unicode 'Import excel files into R. Supports ''.xls'' via the embedded ''libxls''
    C library (http://sourceforge.net/projects/libxls/) and ''.xlsx'' via the embedded
    ''RapidXML'' C++ library (http://rapidxml.sourceforge.net). Works on Windows, Mac
    and Linux without external dependencies.'


# The original CRAN metadata for this package was:

# Package: readxl
# Title: Read Excel Files
# Version: 0.1.0
# Authors@R: c( person("Hadley", "Wickham", ,"hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = "cph", comment = "Copyright holder of all R code and all C/C++ code without explicit copyright attribution"), person("Marcin", "Kalicinski", role = c("ctb", "cph"), comment = "Author of included RapidXML code"), person("Komarov Valery", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("Christophe Leitienne", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("Bob Colbert", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("David Hoerl", role = c("ctb", "cph"), comment = "Author of included libxls code") )
# Description: Import excel files into R. Supports '.xls' via the embedded 'libxls' C library (http://sourceforge.net/projects/libxls/) and '.xlsx' via the embedded 'RapidXML' C++ library (http://rapidxml.sourceforge.net). Works on Windows, Mac and Linux without external dependencies.
# License: GPL-3 + file LICENSE
# LazyData: true
# LinkingTo: Rcpp
# Imports: Rcpp (>= 0.11.5)
# Suggests: testthat
# Packaged: 2015-04-14 13:24:38 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph] (Copyright holder of all R code and all C/C++ code without explicit copyright attribution), Marcin Kalicinski [ctb, cph] (Author of included RapidXML code), Komarov Valery [ctb, cph] (Author of included libxls code), Christophe Leitienne [ctb, cph] (Author of included libxls code), Bob Colbert [ctb, cph] (Author of included libxls code), David Hoerl [ctb, cph] (Author of included libxls code)
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2015-04-14 16:28:42

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
