package:
  name: r-arm
  # Note that conda versions cannot contain -, so any -'s in the version have
  # been replaced with _'s.
  version: "1.8_6"

source:
  fn: arm_1.8-6.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/arm_1.8-6.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/arm/arm_1.8-6.tar.gz


  # You can add a hash for the file here, like md5 or sha1
  # md5: 49448ba4863157652311cc5ea4fea3ea
  # sha1: 3bcfbee008276084cbb37a2b453963c61176a322
  # patches:
   # List any patch files here
   # - fix.patch

build:
  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r
    - r-mass # [not win]
    - r-matrix >=1.0 # [not win]
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme # [not win]

  run:
    - r
    - r-mass # [not win]
    - r-matrix >=1.0 # [not win]
    - r-abind
    - r-coda
    - r-lme4 >=1.0
    - r-nlme # [not win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('arm')" # [not win]
    - "\"%R%\" -e \"library('arm')\"" # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: !!python/unicode 'http://CRAN.R-project.org/package=arm'

  license: GPL (>= 2)
  summary: !!python/unicode 'R functions for processing ''lm'', ''glm'', ''svy.glm'', ''merMod''
    and ''polr'' outputs.'


# The original CRAN metadata for this package was:

# Package: arm
# Version: 1.8-6
# Date: 2015-7-7
# Title: Data Analysis Using Regression and Multilevel/Hierarchical Models
# Authors@R: c(person("Andrew", "Gelman", role = "aut", email = "gelman@stat.columbia.edu"), person("Yu-Sung", "Su", role =  c("aut", "cre"), email = "suyusung@tsinghua.edu.cn"), person("Masanao", "Yajima", role =  "ctb", email = "yajima@stat.ucla.edu"), person("Jennifer", "Hill", role =  "ctb", email = "jennifer.hill@nyu.edu"), person("Maria Grazia", "Pittau", role =  "ctb", email = "grazia@stat.columbia.edu"), person("Jouni", "Kerman", role =  "ctb", email = "jouni@kerman.com"), person("Tian", "Zheng", role =  "ctb", email = "tzheng@stat.columbia.edu"), person("Vicent", "Dorie", role =  "ctb", email = "vjd4@nyu.edu") )
# Author: Andrew Gelman [aut], Yu-Sung Su [aut, cre], Masanao Yajima [ctb], Jennifer Hill [ctb], Maria Grazia Pittau [ctb], Jouni Kerman [ctb], Tian Zheng [ctb], Vicent Dorie [ctb]
# Maintainer: Yu-Sung Su <suyusung@tsinghua.edu.cn>
# Depends: R (>= 3.1.0), MASS, Matrix (>= 1.0), stats, lme4 (>= 1.0)
# Imports: abind, coda, graphics, grDevices, methods, nlme, utils
# Description: R functions for processing 'lm', 'glm', 'svy.glm', 'merMod' and 'polr' outputs.
# URL: http://CRAN.R-project.org/package=arm
# License: GPL (>= 2)
# NeedsCompilation: no
# Packaged: 2015-07-10 22:24:17 UTC; suyusung
# Repository: CRAN
# Date/Publication: 2015-07-11 11:02:14

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
